services:
  sonarqube:
    image: sonarqube:8.9.10-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - ./devops/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties

volumes:
  sonarqube_data:
  sonarqube_extensions: